import React from 'react';
import EventContainer from './_Component/EventContainer';

export const metadata = {
  title: 'Event',
  description: 'Generated by create next app',
};

export default function page() {
  return (
    <div>
      <EventContainer />
    </div>
  );
}
