import ResponsiveContainer from '@/component/ResponsiveContainer/ResponsiveContainer';
import ContactContainer from './_Component/ContactContainer';

export async function generateMetadata() {
  return {
    title: 'Contact',
    description: 'Generated by create next app',
  };
}

export default function Contact() {
  return (
    <ResponsiveContainer>
      <ContactContainer />
    </ResponsiveContainer>
  );
}
