import React from 'react';
import TermsAndCondition from './_Component/TermsAndCondition';

export const metadata = {
  title: 'Terms',
  description: 'Generated by create next app',
};

function page() {
  return (
    <div>
      <TermsAndCondition />
    </div>
  );
}

export default page;
