import React from 'react';
import ProductDetails from '../_Component/ProductDetails';
import RelatedProducts from '../_Component/RelatedProducts';

export const metadata = {
  title: 'Product',
  description: 'Generated by create next app',
};

export default function page() {
  return (
    <div>
      <ProductDetails />
      <RelatedProducts />
    </div>
  );
}
