import React from 'react';
import GalleryPage from './_Component/GalleryContainer';
import ResponsiveContainer from '@/component/ResponsiveContainer/ResponsiveContainer';

export const metadata = {
  title: 'Gallery',
  description: 'Generated by create next app',
};

export default function page() {
  return (
    <ResponsiveContainer>
      <GalleryPage />
    </ResponsiveContainer>
  );
}
