import CommonPageHeader from '@/component/CommonPageHeader/CommonPageHeader';
import ResponsiveContainer from '@/component/ResponsiveContainer/ResponsiveContainer';
import FilterSection from './_Component/ProductFilter';
import ProductContainer from './_Component/ProductContainer';
import ProductFilterWrapper from './_Component/ProductFilterWrap';

export const metadata = {
  title: 'Product',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <ResponsiveContainer>
      <div className="!w-full !max-w-[1280px] !mx-auto !px-5 md:!px-10 lg:!px-0 !my-10">
        {/* Page Header */}
        <CommonPageHeader
          pageTitle="Product"
          previousPage={{
            pageTitle: 'Home',
            pageRoute: '/',
          }}
        />

        <ProductFilterWrapper />
      </div>
    </ResponsiveContainer>
  );
}
