import CommonPageHeader from '@/component/CommonPageHeader/CommonPageHeader';
import ResponsiveContainer from '@/component/ResponsiveContainer/ResponsiveContainer';
import FilterSection from './_Component/ProductFilter';
import ProductContainer from './_Component/ProductContainer';

export const metadata = {
  title: 'Product',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <ResponsiveContainer>
      <div className="!w-full !max-w-[1280px] !mx-auto !px-5 md:!px-10 lg:!px-0 !my-10">
        {/* Page Header */}
        <CommonPageHeader
          pageTitle="Product"
          previousPage={{
            pageTitle: 'Home',
            pageRoute: '/',
          }}
        />

        {/* Filter + Products Section */}
        <div className="!mt-10 flex flex-col lg:flex-row lg:gap-x-10 w-full">
          {/* Filter */}
          <div className="w-full lg:w-1/4 !mb-8 lg:!mb-0">
            <FilterSection />
          </div>

          {/* Products */}
          <div className="w-full lg:w-3/4">
            <ProductContainer />
          </div>
        </div>
      </div>
    </ResponsiveContainer>
  );
}
