import EventDetailsPage from '../_Component/EventDetailsPage';

export const metadata = {
  title: 'Event',
  description: 'Generated by create next app',
};

export default function page() {
  return (
    <div>
      <EventDetailsPage />
    </div>
  );
}
