import ArticleDetailsPage from '../_Component/ArticleDetails';

export const metadata = {
  title: 'Event',
  description: 'Generated by create next app',
};

export default function page() {
  return (
    <div>
      <ArticleDetailsPage />
    </div>
  );
}
