import React from 'react';
import PrivacyPolicy from './_Component/Privacypolicy';
export const metadata = {
  title: 'Privacy',
  description: 'Generated by create next app',
};
function page() {
  return (
    <div>
      <PrivacyPolicy />
    </div>
  );
}

export default page;
