import React from 'react';
import CartPage from './_component/CartContainer';
import ResponsiveContainer from '@/component/ResponsiveContainer/ResponsiveContainer';

export const metadata = {
  title: 'Cart',
  description: 'Generated by create next app',
};

export default function page() {
  return (
    <ResponsiveContainer>
      <CartPage />
    </ResponsiveContainer>
  );
}
