import React from 'react';
import AricleContainer from './_Component/AricleContainer';

export const metadata = {
  title: 'Finance Article',
  description: 'Generated by create next app',
};

const page = () => {
  return (
    <div>
      <AricleContainer />
    </div>
  );
};

export default page;
